#!/usr/bin/env python3
from __future__ import annotations

import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "site"
SOURCE_CFG = ROOT / "monitor" / "sources.json"
BASE = "https://guia-migrante-pt.pages.dev"
REVIEW_DATE = "20/08/2026"
REVIEW_ISO = "2026-08-20"

PAGES = [
    "404.html",
    "acessibilidade.html",
    "atualizacoes.html",
    "discriminacao-apoio.html",
    "escola-familias.html",
    "estado-informacao.html",
    "impostos.html",
    "mudanca-saida.html",
    "portugues.html",
    "privacidade.html",
    "registos-civis.html",
    "situacoes-urgentes.html",
    "termos.html",
    "viver-em-portugal.html",
]

UI = {
    "fr": {"name":"Français","stage":"Traduction en cours — cette page reste hors index et hors du sélecteur public jusqu’à la fin de la révision complète.","verified":f"Vérifié le {REVIEW_DATE}","independent":"Information indépendante · Sources officielles","home":"Accueil","routes":"Parcours","daily":"Vie quotidienne","contacts":"Contacts","faq":"FAQ","security":"Éviter les arnaques","practical":"À retenir","official":"Sources officielles","check":"Vérifiez toujours la source officielle avant d’agir.","source":"Source officielle ↗","menu":"Ouvrir le menu","skip":"Aller au contenu principal","legal":"Guia Migrante PT est un portail indépendant. En cas de divergence, la législation applicable et l’information de l’autorité compétente prévalent."},
    "es": {"name":"Español","stage":"Traducción en curso — esta página permanece fuera del índice y del selector público hasta completar la revisión.","verified":f"Verificado el {REVIEW_DATE}","independent":"Información independiente · Fuentes oficiales","home":"Inicio","routes":"Rutas","daily":"Día a día","contacts":"Contactos","faq":"Preguntas frecuentes","security":"Evitar estafas","practical":"Puntos clave","official":"Fuentes oficiales","check":"Comprueba siempre la fuente oficial antes de actuar.","source":"Fuente oficial ↗","menu":"Abrir menú","skip":"Saltar al contenido principal","legal":"Guia Migrante PT es un portal independiente. En caso de divergencia, prevalecen la legislación aplicable y la información de la autoridad competente."},
    "uk": {"name":"Українська","stage":"Переклад триває — сторінка залишається поза індексацією та публічним вибором мов до завершення повної перевірки.","verified":f"Перевірено {REVIEW_DATE}","independent":"Незалежна інформація · Офіційні джерела","home":"Головна","routes":"Маршрути","daily":"Щоденні справи","contacts":"Контакти","faq":"Поширені питання","security":"Уникнення шахрайства","practical":"Головне","official":"Офіційні джерела","check":"Перед будь-якими діями завжди перевіряйте офіційне джерело.","source":"Офіційне джерело ↗","menu":"Відкрити меню","skip":"Перейти до основного вмісту","legal":"Guia Migrante PT — незалежний портал. У разі розбіжностей перевагу мають чинне законодавство та інформація компетентного органу."},
    "ru": {"name":"Русский","stage":"Перевод продолжается — страница остаётся вне индексации и публичного выбора языков до завершения полной проверки.","verified":f"Проверено {REVIEW_DATE}","independent":"Независимая информация · Официальные источники","home":"Главная","routes":"Маршруты","daily":"Повседневные вопросы","contacts":"Контакты","faq":"Частые вопросы","security":"Как избежать мошенничества","practical":"Главное","official":"Официальные источники","check":"Перед любыми действиями всегда проверяйте официальный источник.","source":"Официальный источник ↗","menu":"Открыть меню","skip":"Перейти к основному содержанию","legal":"Guia Migrante PT — независимый портал. При расхождениях приоритет имеют действующее законодательство и информация компетентного органа."},
    "hi": {"name":"हिन्दी","stage":"अनुवाद जारी है — पूरी समीक्षा पूरी होने तक यह पृष्ठ इंडेक्स और सार्वजनिक भाषा चयन से बाहर रहेगा।","verified":f"सत्यापित: {REVIEW_DATE}","independent":"स्वतंत्र जानकारी · आधिकारिक स्रोत","home":"मुखपृष्ठ","routes":"मार्ग","daily":"दैनिक जीवन","contacts":"संपर्क","faq":"सामान्य प्रश्न","security":"धोखाधड़ी से बचें","practical":"मुख्य बातें","official":"आधिकारिक स्रोत","check":"कोई कदम उठाने से पहले हमेशा आधिकारिक स्रोत जाँचें।","source":"आधिकारिक स्रोत ↗","menu":"मेनू खोलें","skip":"मुख्य सामग्री पर जाएँ","legal":"Guia Migrante PT एक स्वतंत्र पोर्टल है। किसी अंतर की स्थिति में लागू कानून और सक्षम प्राधिकरण की आधिकारिक जानकारी को प्राथमिकता दी जाती है।"},
    "bn": {"name":"বাংলা","stage":"অনুবাদ চলছে — পূর্ণ পর্যালোচনা শেষ না হওয়া পর্যন্ত এই পৃষ্ঠা ইনডেক্স ও পাবলিক ভাষা-নির্বাচনের বাইরে থাকবে।","verified":f"যাচাই করা হয়েছে: {REVIEW_DATE}","independent":"স্বাধীন তথ্য · সরকারি উৎস","home":"হোম","routes":"পথসমূহ","daily":"দৈনন্দিন জীবন","contacts":"যোগাযোগ","faq":"সাধারণ প্রশ্ন","security":"প্রতারণা এড়ান","practical":"মূল বিষয়","official":"সরকারি উৎস","check":"কোনো পদক্ষেপ নেওয়ার আগে সবসময় সরকারি উৎস যাচাই করুন।","source":"সরকারি উৎস ↗","menu":"মেনু খুলুন","skip":"মূল বিষয়বস্তুতে যান","legal":"Guia Migrante PT একটি স্বাধীন পোর্টাল। কোনো অমিল হলে প্রযোজ্য আইন এবং সংশ্লিষ্ট কর্তৃপক্ষের সরকারি তথ্য অগ্রাধিকার পায়।"},
}

DATA = {
"fr": {
"404.html":("Page introuvable","La page demandée n’existe pas ou a été déplacée.",[("Retour à l’accueil","Revenez à la page d’accueil et utilisez les parcours ou la recherche pour retrouver l’information."),("Liens enregistrés","Si vous avez utilisé un ancien favori, ouvrez à nouveau la rubrique correspondante depuis le menu."),("Besoin d’aide","Utilisez la page Contacts pour identifier le canal officiel adapté.")]),
"acessibilidade.html":("Accessibilité","Le Guia Migrante PT vise une navigation claire, lisible et utilisable au clavier, sur mobile et avec les technologies d’assistance.",[("Structure claire","Les pages utilisent des titres, liens et boutons avec des libellés compréhensibles."),("Clavier et contraste","La navigation et les éléments interactifs sont conçus pour rester utilisables sans souris et avec un contraste lisible."),("Amélioration continue","Les problèmes d’accessibilité détectés sont corrigés dans les versions suivantes du site.")]),
"atualizacoes.html":("Mises à jour","Cette page regroupe les changements importants du Guia et les informations qui ont été revérifiées à partir de sources officielles.",[("Ce qui change","Les informations sensibles sont revues lorsque les autorités publient de nouvelles règles ou procédures."),("Date de révision","Chaque page importante indique sa dernière date de vérification."),("Sources officielles","Une modification n’est pas publiée comme fait établi sans source officielle suffisante.")]),
"discriminacao-apoio.html":("Discrimination et soutien","La discrimination fondée notamment sur l’origine, la nationalité, la couleur, la langue ou d’autres motifs peut être signalée par les canaux compétents.",[("Conservez les preuves","Gardez messages, documents, dates, lieux et témoins utiles."),("Choisissez le bon canal","Selon la situation, il peut être pertinent de contacter la CIG, l’ACT, la police, un service public ou une structure d’appui."),("Danger immédiat","En cas de danger immédiat, utilisez les services d’urgence appropriés.")]),
"escola-familias.html":("École et familles","L’inscription scolaire, l’équivalence d’études, les aides et l’accompagnement des enfants dépendent de l’âge et de la situation scolaire.",[("Inscription","Contactez l’école ou les services compétents de l’éducation pour connaître la procédure applicable."),("Documents scolaires","Conservez certificats, relevés, documents d’identité et informations sur la scolarité antérieure."),("Soutien familial","Les besoins particuliers, la langue et les aides sociales peuvent relever de dispositifs différents.")]),
"estado-informacao.html":("État de l’information","Le Guia distingue l’information vérifiée, les sources temporairement indisponibles et les changements qui nécessitent une révision humaine.",[("Vérifié","Le contenu repose sur une source officielle consultée et une date de contrôle."),("Source indisponible","Une panne ou un blocage temporaire ne supprime pas automatiquement la dernière information officielle valide."),("Révision nécessaire","Les changements sensibles sont mis en attente jusqu’à vérification avant publication.")]),
"impostos.html":("Impôts et obligations fiscales","NIF, résidence fiscale, activité professionnelle et déclarations sont des sujets différents. Les obligations dépendent de la situation concrète de chaque personne.",[("Résidence fiscale","Elle ne doit pas être déduite uniquement du fait de posséder un NIF."),("Activité et revenus","Travail salarié, activité indépendante et autres revenus peuvent avoir des obligations différentes."),("Portal das Finanças","Utilisez les canaux officiels de l’Autoridade Tributária pour les règles, déclarations et données personnelles.")]),
"mudanca-saida.html":("Changement d’adresse et départ du Portugal","Un changement d’adresse ou un départ peut impliquer des mises à jour auprès de plusieurs organismes, et pas seulement de l’AIMA.",[("Adresse","Vérifiez les obligations de mise à jour auprès des organismes qui utilisent votre adresse officielle."),("Fiscalité et sécurité sociale","Un départ peut avoir des effets sur la résidence fiscale, les cotisations ou les prestations."),("Documents de séjour","Confirmez auprès de l’autorité compétente les effets d’une absence prolongée sur votre titre ou statut.")]),
"portugues.html":("Apprendre le portugais","Apprendre le portugais facilite l’accès aux services, au travail, à l’école et à la vie quotidienne.",[("Cours officiels et locaux","Recherchez les programmes publics, municipaux, associatifs ou de formation disponibles dans votre zone."),("Niveau adapté","Choisissez le cours selon votre niveau et votre objectif: quotidien, emploi, études ou certification."),("Pratique régulière","La pratique quotidienne complète les cours et accélère l’autonomie.")]),
"privacidade.html":("Confidentialité","Le Guia est conçu pour fournir des informations publiques sans exiger de compte ni le téléchargement de documents personnels sensibles.",[("Données minimales","N’envoyez pas de passeports, titres de séjour, mots de passe ou codes d’accès via les outils publics du Guia."),("Outils locaux","Lorsque cela est indiqué, certaines préférences ou listes peuvent être conservées uniquement dans votre navigateur."),("Services externes","Les sites officiels vers lesquels le Guia renvoie appliquent leurs propres politiques de confidentialité.")]),
"registos-civis.html":("Registres civils","Naissance, mariage, décès et autres actes d’état civil suivent les règles de l’IRN/Justiça et peuvent nécessiter des documents étrangers authentifiés ou traduits.",[("Acte concerné","La procédure dépend du type de registre ou de certificat demandé."),("Documents étrangers","Selon le cas, une apostille, légalisation ou traduction peut être nécessaire."),("Canal officiel","Vérifiez le service compétent de la Justiça/IRN avant de remettre des originaux ou de payer.")]),
"situacoes-urgentes.html":("Situations urgentes","En cas de danger, urgence médicale, violence, disparition de documents ou autre situation critique, utilisez d’abord le canal adapté à l’urgence.",[("Danger immédiat","Au Portugal, le 112 est le numéro européen d’urgence."),("Santé","Pour les situations non immédiatement vitales, utilisez les canaux officiels de santé pour être orienté correctement."),("Documents et sécurité","En cas de vol ou perte, conservez les preuves et contactez les autorités et organismes émetteurs concernés.")]),
"termos.html":("Conditions d’utilisation","Le Guia fournit une orientation générale et ne remplace pas une décision administrative, un avis juridique individuel ou l’information officielle de l’autorité compétente.",[("Pas de garantie de résultat","Le Guia ne peut pas garantir un rendez-vous, une autorisation, un visa, une nationalité ou toute autre décision."),("Sources et dates","Les contenus sont révisés, mais les règles peuvent changer entre deux vérifications."),("Utilisation responsable","Avant une démarche sensible, confirmez toujours les conditions actuelles auprès de la source officielle.")]),
"viver-em-portugal.html":("Vivre au Portugal","Après les démarches migratoires, la vie quotidienne comprend santé, travail, logement, fiscalité, école, langue, banque, services essentiels et droits du consommateur.",[("Organiser les priorités","Commencez par les besoins urgents: logement sûr, santé, travail, documents et scolarité."),("Utiliser les bons services","Chaque sujet relève d’une autorité ou d’un service différent; évitez de traiter tous les problèmes comme une question AIMA."),("Conserver les preuves","Contrats, reçus, déclarations, notifications et documents officiels doivent être conservés de façon organisée.")]),
},
"es": {
"404.html":("Página no encontrada","La página solicitada no existe o se ha movido.",[("Volver al inicio","Regresa al inicio y usa las rutas o la búsqueda para encontrar la información."),("Enlaces antiguos","Si usaste un favorito antiguo, abre de nuevo la sección correspondiente desde el menú."),("Necesitas ayuda","Usa Contactos para identificar el canal oficial adecuado.")]),
"acessibilidade.html":("Accesibilidad","Guia Migrante PT busca ofrecer una navegación clara, legible y utilizable con teclado, móvil y tecnologías de apoyo.",[("Estructura clara","Las páginas usan títulos, enlaces y botones con nombres comprensibles."),("Teclado y contraste","La navegación está pensada para funcionar sin ratón y con contraste legible."),("Mejora continua","Los problemas de accesibilidad detectados se corrigen en versiones posteriores.")]),
"atualizacoes.html":("Actualizaciones","Esta página reúne cambios importantes del Guia e información revisada de nuevo a partir de fuentes oficiales.",[("Qué cambia","La información sensible se revisa cuando las autoridades publican nuevas reglas o procedimientos."),("Fecha de revisión","Las páginas importantes muestran la última fecha de comprobación."),("Fuentes oficiales","Un cambio no se publica como hecho confirmado sin respaldo oficial suficiente.")]),
"discriminacao-apoio.html":("Discriminación y apoyo","La discriminación por origen, nacionalidad, color, lengua u otros motivos puede denunciarse por los canales competentes.",[("Guarda pruebas","Conserva mensajes, documentos, fechas, lugares y posibles testigos."),("Elige el canal adecuado","Según el caso puede corresponder CIG, ACT, policía, un servicio público o una entidad de apoyo."),("Peligro inmediato","Si existe peligro inmediato, usa los servicios de emergencia adecuados.")]),
"escola-familias.html":("Escuela y familias","La matrícula escolar, equivalencias, ayudas y apoyo a menores dependen de la edad y de la situación educativa.",[("Matrícula","Contacta con la escuela o con los servicios educativos competentes para conocer el procedimiento."),("Documentación escolar","Conserva certificados, notas, identificación y datos sobre la escolaridad anterior."),("Apoyo familiar","Necesidades especiales, idioma y ayudas sociales pueden pertenecer a programas distintos.")]),
"estado-informacao.html":("Estado de la información","El Guia diferencia entre información verificada, fuentes temporalmente inaccesibles y cambios que requieren revisión humana.",[("Verificada","El contenido se apoya en una fuente oficial y una fecha de comprobación."),("Fuente inaccesible","Un fallo temporal no elimina automáticamente la última información oficial válida."),("Revisión necesaria","Los cambios sensibles quedan pendientes hasta ser verificados antes de publicarse.")]),
"impostos.html":("Impuestos y obligaciones fiscales","NIF, residencia fiscal, actividad profesional y declaraciones son asuntos diferentes. Las obligaciones dependen de la situación concreta.",[("Residencia fiscal","No debe deducirse solo por tener un NIF."),("Actividad e ingresos","Trabajo por cuenta ajena, actividad independiente y otros ingresos pueden tener obligaciones distintas."),("Portal das Finanças","Usa los canales oficiales de la Autoridade Tributária para reglas, declaraciones y datos personales.")]),
"mudanca-saida.html":("Cambio de dirección y salida de Portugal","Cambiar de dirección o salir del país puede exigir actualizaciones ante varios organismos, no solo AIMA.",[("Dirección","Comprueba las obligaciones de actualización con los organismos que usan tu domicilio oficial."),("Fiscalidad y Seguridad Social","La salida puede afectar residencia fiscal, cotizaciones o prestaciones."),("Documentos de residencia","Confirma con la autoridad competente los efectos de ausencias prolongadas sobre tu título o estatuto.")]),
"portugues.html":("Aprender portugués","Aprender portugués facilita el acceso a servicios, trabajo, escuela y vida diaria.",[("Cursos oficiales y locales","Busca programas públicos, municipales, asociativos o formativos disponibles en tu zona."),("Nivel adecuado","Elige según tu nivel y objetivo: vida diaria, empleo, estudios o certificación."),("Práctica regular","La práctica diaria complementa los cursos y acelera la autonomía.")]),
"privacidade.html":("Privacidad","El Guia ofrece información pública sin exigir cuenta ni cargar documentos personales sensibles.",[("Datos mínimos","No envíes pasaportes, tarjetas de residencia, contraseñas o códigos de acceso a través de herramientas públicas."),("Herramientas locales","Cuando se indique, algunas preferencias o listas pueden guardarse solo en tu navegador."),("Servicios externos","Las webs oficiales enlazadas aplican sus propias políticas de privacidad.")]),
"registos-civis.html":("Registro civil","Nacimiento, matrimonio, defunción y otros actos civiles siguen las reglas del IRN/Justiça y pueden requerir documentos extranjeros autenticados o traducidos.",[("Tipo de acto","El procedimiento depende del registro o certificado que necesites."),("Documentos extranjeros","Según el caso puede hacer falta apostilla, legalización o traducción."),("Canal oficial","Comprueba el servicio competente de Justiça/IRN antes de entregar originales o pagar.")]),
"situacoes-urgentes.html":("Situaciones urgentes","Ante peligro, urgencia médica, violencia, pérdida de documentos u otra situación crítica, usa primero el canal adecuado a la urgencia.",[("Peligro inmediato","En Portugal, 112 es el número europeo de emergencias."),("Salud","Para situaciones no vitales, usa los canales oficiales de salud para recibir orientación."),("Documentos y seguridad","En caso de robo o pérdida, conserva pruebas y contacta a las autoridades y organismos emisores.")]),
"termos.html":("Condiciones de uso","El Guia ofrece orientación general y no sustituye decisiones administrativas, asesoramiento jurídico individual ni información oficial de la autoridad competente.",[("Sin garantía de resultado","El Guia no puede garantizar cita, autorización, visado, nacionalidad ni otra decisión."),("Fuentes y fechas","Los contenidos se revisan, pero las reglas pueden cambiar entre revisiones."),("Uso responsable","Antes de un trámite sensible, confirma siempre las condiciones actuales en la fuente oficial.")]),
"viver-em-portugal.html":("Vivir en Portugal","Después de los trámites migratorios, la vida diaria incluye salud, trabajo, vivienda, impuestos, escuela, idioma, banca, servicios esenciales y derechos del consumidor.",[("Ordena prioridades","Empieza por necesidades urgentes: vivienda segura, salud, trabajo, documentos y escolarización."),("Usa el servicio correcto","Cada tema corresponde a una autoridad diferente; no trates todos los problemas como asuntos de AIMA."),("Guarda documentos","Conserva contratos, recibos, declaraciones, notificaciones y documentos oficiales de forma organizada.")]),
},
}

# Compact but native-language equivalents for UK/RU/HI/BN. The factual scope is
# intentionally conservative while the languages are staged.
DATA["uk"] = {
"404.html":("Сторінку не знайдено","Запитувана сторінка не існує або була переміщена.",[("Повернутися на головну","Скористайтеся головною сторінкою, маршрутами або пошуком."),("Старе посилання","Якщо це старе збережене посилання, відкрийте потрібний розділ через меню."),("Потрібна допомога","На сторінці контактів можна знайти відповідний офіційний канал.")]),
"acessibilidade.html":("Доступність","Guia Migrante PT прагне бути зрозумілим, читабельним і придатним для клавіатури, мобільних пристроїв та допоміжних технологій.",[("Зрозуміла структура","Заголовки, посилання та кнопки мають зрозумілі назви."),("Клавіатура і контраст","Навігація має працювати без миші та залишатися читабельною."),("Постійне покращення","Виявлені проблеми доступності виправляються в наступних версіях.")]),
"atualizacoes.html":("Оновлення","Тут зібрано важливі зміни Guia та інформацію, повторно перевірену за офіційними джерелами.",[("Що змінюється","Чутлива інформація переглядається після нових правил або процедур органів влади."),("Дата перевірки","Важливі сторінки показують дату останньої перевірки."),("Офіційні джерела","Зміна не публікується як підтверджений факт без достатньої офіційної підстави.")]),
"discriminacao-apoio.html":("Дискримінація та підтримка","Про дискримінацію за походженням, громадянством, мовою чи іншими ознаками можна повідомити компетентним органам.",[("Зберігайте докази","Збережіть повідомлення, документи, дати, місця та дані свідків."),("Оберіть правильний канал","Залежно від ситуації це може бути CIG, ACT, поліція, державна служба або служба підтримки."),("Негайна небезпека","У разі безпосередньої небезпеки використовуйте екстрені служби.")]),
"escola-familias.html":("Школа та сім’я","Зарахування до школи, визнання навчання та підтримка дітей залежать від віку і освітньої ситуації.",[("Зарахування","Зверніться до школи або компетентної освітньої служби."),("Шкільні документи","Зберігайте довідки, оцінки, посвідчення особи та дані про попереднє навчання."),("Підтримка сім’ї","Мовна підтримка, особливі потреби та соціальна допомога можуть мати окремі програми.")]),
"estado-informacao.html":("Стан інформації","Guia розрізняє перевірену інформацію, тимчасово недоступні джерела та зміни, що потребують ручної перевірки.",[("Перевірено","Матеріал має офіційне джерело та дату перевірки."),("Джерело недоступне","Тимчасовий збій не видаляє автоматично останню чинну офіційну інформацію."),("Потрібна перевірка","Чутливі зміни не публікуються до перевірки.")]),
"impostos.html":("Податки та податкові обов’язки","NIF, податкове резидентство, професійна діяльність і декларації — різні питання, що залежать від конкретної ситуації.",[("Податкове резидентство","Його не слід визначати лише за наявністю NIF."),("Діяльність і доходи","Наймана праця, самозайнятість та інші доходи можуть мати різні обов’язки."),("Portal das Finanças","Для правил і декларацій використовуйте офіційні канали податкової служби.")]),
"mudanca-saida.html":("Зміна адреси та виїзд з Португалії","Зміна адреси або виїзд можуть вимагати оновлень у кількох установах, а не лише в AIMA.",[("Адреса","Перевірте вимоги установ, які використовують вашу офіційну адресу."),("Податки і соцзабезпечення","Виїзд може вплинути на податкове резидентство, внески або виплати."),("Документи на проживання","Уточніть наслідки тривалої відсутності для вашого статусу.")]),
"portugues.html":("Вивчення португальської мови","Португальська мова полегшує доступ до послуг, роботи, школи та повсякденного життя.",[("Курси","Шукайте державні, муніципальні, громадські або навчальні програми."),("Рівень","Оберіть курс за рівнем і метою: побут, робота, навчання чи сертифікація."),("Практика","Регулярна практика прискорює самостійність.")]),
"privacidade.html":("Конфіденційність","Guia надає публічну інформацію без обов’язкового облікового запису та без завантаження чутливих документів.",[("Мінімум даних","Не надсилайте паспорти, картки проживання, паролі чи коди доступу через публічні інструменти Guia."),("Локальні інструменти","Деякі налаштування можуть зберігатися лише у вашому браузері."),("Зовнішні сайти","Офіційні сайти мають власні політики конфіденційності.")]),
"registos-civis.html":("Цивільна реєстрація","Народження, шлюб, смерть та інші акти цивільного стану регулюються IRN/Justiça і можуть вимагати засвідчених або перекладених іноземних документів.",[("Тип акта","Процедура залежить від потрібного запису або свідоцтва."),("Іноземні документи","Може знадобитися апостиль, легалізація або переклад."),("Офіційний канал","Перевірте компетентну службу Justiça/IRN перед передачею оригіналів або оплатою.")]),
"situacoes-urgentes.html":("Невідкладні ситуації","У разі небезпеки, медичної невідкладності, насильства або втрати документів спочатку використовуйте відповідний екстрений канал.",[("Негайна небезпека","У Португалії номер екстреної допомоги — 112."),("Здоров’я","Для не критичних випадків використовуйте офіційні медичні канали."),("Документи","У разі крадіжки або втрати зберігайте докази та звертайтеся до відповідних органів.")]),
"termos.html":("Умови використання","Guia надає загальну орієнтацію і не замінює адміністративне рішення, індивідуальну юридичну консультацію чи офіційну інформацію органу влади.",[("Без гарантії результату","Guia не гарантує запис, дозвіл, візу, громадянство чи інше рішення."),("Джерела і дати","Правила можуть змінитися між перевірками."),("Відповідальне використання","Перед важливою дією підтвердьте актуальні умови в офіційному джерелі.")]),
"viver-em-portugal.html":("Життя в Португалії","Після міграційних процедур повсякденне життя включає здоров’я, роботу, житло, податки, школу, мову, банки, комунальні послуги та права споживача.",[("Пріоритети","Почніть із безпечного житла, здоров’я, роботи, документів і школи."),("Правильна служба","Кожна тема має свій компетентний орган; не всі питання належать AIMA."),("Зберігайте документи","Організовано зберігайте договори, квитанції, повідомлення та офіційні документи.")]),
}

DATA["ru"] = {
"404.html":("Страница не найдена","Запрошенная страница не существует или была перемещена.",[("Вернуться на главную","Используйте главную страницу, маршруты или поиск."),("Старая ссылка","Если это старое сохранённое приглашение, откройте нужный раздел через меню."),("Нужна помощь","На странице контактов можно найти подходящий официальный канал.")]),
"acessibilidade.html":("Доступность","Guia Migrante PT стремится быть понятным, читаемым и доступным с клавиатуры, мобильных устройств и вспомогательных технологий.",[("Понятная структура","Заголовки, ссылки и кнопки имеют понятные названия."),("Клавиатура и контраст","Навигация должна работать без мыши и оставаться читаемой."),("Постоянное улучшение","Выявленные проблемы доступности исправляются в следующих версиях.")]),
"atualizacoes.html":("Обновления","Здесь собраны важные изменения Guia и сведения, повторно проверенные по официальным источникам.",[("Что меняется","Чувствительная информация пересматривается после публикации новых правил или процедур."),("Дата проверки","На важных страницах указана дата последней проверки."),("Официальные источники","Изменение не публикуется как подтверждённый факт без достаточного официального основания.")]),
"discriminacao-apoio.html":("Дискриминация и поддержка","О дискриминации по происхождению, гражданству, языку и другим признакам можно сообщать через компетентные каналы.",[("Сохраняйте доказательства","Храните сообщения, документы, даты, места и данные свидетелей."),("Выберите правильный канал","В зависимости от ситуации это может быть CIG, ACT, полиция, государственная служба или служба поддержки."),("Немедленная опасность","При непосредственной опасности используйте экстренные службы.")]),
"escola-familias.html":("Школа и семья","Зачисление в школу, признание обучения и поддержка детей зависят от возраста и образовательной ситуации.",[("Зачисление","Обратитесь в школу или компетентную образовательную службу."),("Документы","Храните справки, оценки, документы личности и сведения о предыдущем обучении."),("Поддержка семьи","Языковая поддержка, особые потребности и социальная помощь могут относиться к разным программам.")]),
"estado-informacao.html":("Статус информации","Guia различает проверенную информацию, временно недоступные источники и изменения, требующие ручной проверки.",[("Проверено","Материал имеет официальный источник и дату проверки."),("Источник недоступен","Временный сбой не удаляет автоматически последнюю действующую официальную информацию."),("Нужна проверка","Чувствительные изменения не публикуются до проверки.")]),
"impostos.html":("Налоги и налоговые обязанности","NIF, налоговое резидентство, профессиональная деятельность и декларации — разные вопросы, зависящие от конкретной ситуации.",[("Налоговое резидентство","Его нельзя определять только по наличию NIF."),("Доходы и деятельность","Работа по найму, самозанятость и другие доходы могут иметь разные обязанности."),("Portal das Finanças","Для правил и деклараций используйте официальные каналы налоговой службы.")]),
"mudanca-saida.html":("Смена адреса и выезд из Португалии","Смена адреса или выезд могут потребовать обновления данных в нескольких учреждениях, а не только в AIMA.",[("Адрес","Проверьте требования учреждений, использующих ваш официальный адрес."),("Налоги и соцобеспечение","Выезд может повлиять на налоговое резидентство, взносы или выплаты."),("Документы на проживание","Уточните последствия длительного отсутствия для вашего статуса.")]),
"portugues.html":("Изучение португальского языка","Португальский язык облегчает доступ к услугам, работе, школе и повседневной жизни.",[("Курсы","Ищите государственные, муниципальные, общественные или учебные программы."),("Уровень","Выбирайте курс по уровню и цели: быт, работа, учёба или сертификация."),("Практика","Регулярная практика ускоряет самостоятельность.")]),
"privacidade.html":("Конфиденциальность","Guia предоставляет публичную информацию без обязательного аккаунта и без загрузки чувствительных документов.",[("Минимум данных","Не отправляйте паспорта, карты ВНЖ, пароли или коды доступа через публичные инструменты Guia."),("Локальные инструменты","Некоторые настройки могут храниться только в вашем браузере."),("Внешние сайты","Официальные сайты применяют собственные политики конфиденциальности.")]),
"registos-civis.html":("Гражданская регистрация","Рождение, брак, смерть и другие акты регулируются IRN/Justiça и могут требовать заверенных или переведённых иностранных документов.",[("Тип акта","Процедура зависит от нужной записи или свидетельства."),("Иностранные документы","Могут потребоваться апостиль, легализация или перевод."),("Официальный канал","Проверьте компетентную службу Justiça/IRN до передачи оригиналов или оплаты.")]),
"situacoes-urgentes.html":("Экстренные ситуации","При опасности, медицинской экстренной ситуации, насилии или утрате документов сначала используйте соответствующий срочный канал.",[("Немедленная опасность","В Португалии номер экстренной помощи — 112."),("Здоровье","Для не критических случаев используйте официальные медицинские каналы."),("Документы","При краже или утрате сохраняйте доказательства и обращайтесь в соответствующие органы.")]),
"termos.html":("Условия использования","Guia даёт общую ориентацию и не заменяет административное решение, индивидуальную юридическую консультацию или официальную информацию органа власти.",[("Без гарантии результата","Guia не гарантирует запись, разрешение, визу, гражданство или иное решение."),("Источники и даты","Правила могут измениться между проверками."),("Ответственное использование","Перед важным действием подтвердите актуальные условия в официальном источнике.")]),
"viver-em-portugal.html":("Жизнь в Португалии","После миграционных процедур повседневная жизнь включает здоровье, работу, жильё, налоги, школу, язык, банки, коммунальные услуги и права потребителя.",[("Приоритеты","Начните с безопасного жилья, здоровья, работы, документов и школы."),("Правильная служба","У каждой темы свой компетентный орган; не все вопросы относятся к AIMA."),("Храните документы","Организованно сохраняйте договоры, квитанции, уведомления и официальные документы.")]),
}

DATA["hi"] = {
"404.html":("पृष्ठ नहीं मिला","माँगा गया पृष्ठ मौजूद नहीं है या स्थानांतरित कर दिया गया है।",[("मुखपृष्ठ पर लौटें","मुखपृष्ठ, मार्ग या खोज का उपयोग करें।"),("पुराना लिंक","यदि आपने पुराना बुकमार्क इस्तेमाल किया है तो मेनू से संबंधित अनुभाग फिर खोलें।"),("मदद चाहिए","संपर्क पृष्ठ पर सही आधिकारिक चैनल खोजें।")]),
"acessibilidade.html":("सुलभता","Guia Migrante PT का लक्ष्य स्पष्ट, पढ़ने योग्य और कीबोर्ड, मोबाइल तथा सहायक तकनीकों के साथ उपयोग करने योग्य होना है।",[("स्पष्ट संरचना","शीर्षक, लिंक और बटन समझने योग्य नामों के साथ बनाए गए हैं।"),("कीबोर्ड और कॉन्ट्रास्ट","नेविगेशन बिना माउस के भी उपयोग योग्य और पढ़ने योग्य रहना चाहिए।"),("लगातार सुधार","मिली हुई सुलभता समस्याएँ अगली रिलीज़ में ठीक की जाती हैं।")]),
"atualizacoes.html":("अपडेट","यह पृष्ठ Guia के महत्वपूर्ण बदलाव और आधिकारिक स्रोतों से दोबारा जाँची गई जानकारी दिखाता है।",[("क्या बदलता है","संवेदनशील जानकारी को नई आधिकारिक प्रक्रियाओं या नियमों के बाद फिर जाँचा जाता है।"),("समीक्षा तिथि","महत्वपूर्ण पृष्ठ अंतिम जाँच की तारीख दिखाते हैं।"),("आधिकारिक स्रोत","पर्याप्त आधिकारिक आधार के बिना बदलाव को पुष्टि किए गए तथ्य के रूप में प्रकाशित नहीं किया जाता।")]),
"discriminacao-apoio.html":("भेदभाव और सहायता","मूल, राष्ट्रीयता, भाषा या अन्य आधार पर भेदभाव की शिकायत सक्षम चैनलों के माध्यम से की जा सकती है।",[("सबूत रखें","संदेश, दस्तावेज़, तारीख, स्थान और गवाहों की जानकारी सुरक्षित रखें।"),("सही चैनल चुनें","मामले के अनुसार CIG, ACT, पुलिस, सार्वजनिक सेवा या सहायता संस्था उपयुक्त हो सकती है।"),("तत्काल खतरा","तत्काल खतरे में आपातकालीन सेवाओं का उपयोग करें।")]),
"escola-familias.html":("स्कूल और परिवार","स्कूल में प्रवेश, पढ़ाई की मान्यता और बच्चों की सहायता उम्र और शैक्षिक स्थिति पर निर्भर करती है।",[("प्रवेश","स्कूल या संबंधित शिक्षा सेवा से प्रक्रिया की पुष्टि करें।"),("स्कूल दस्तावेज़","प्रमाणपत्र, अंकपत्र, पहचान और पिछली पढ़ाई की जानकारी संभाल कर रखें।"),("परिवार सहायता","भाषा, विशेष आवश्यकता और सामाजिक सहायता के लिए अलग कार्यक्रम हो सकते हैं।")]),
"estado-informacao.html":("जानकारी की स्थिति","Guia सत्यापित जानकारी, अस्थायी रूप से अनुपलब्ध स्रोत और मानव समीक्षा की जरूरत वाले बदलावों को अलग-अलग दिखाता है।",[("सत्यापित","सामग्री के पास आधिकारिक स्रोत और जाँच की तारीख होती है।"),("स्रोत अनुपलब्ध","अस्थायी तकनीकी समस्या अंतिम वैध आधिकारिक जानकारी को अपने-आप नहीं हटाती।"),("समीक्षा आवश्यक","संवेदनशील बदलाव जाँच से पहले प्रकाशित नहीं होते।")]),
"impostos.html":("कर और कर दायित्व","NIF, कर-निवास, पेशेवर गतिविधि और घोषणाएँ अलग विषय हैं और आपकी वास्तविक स्थिति पर निर्भर करते हैं।",[("कर-निवास","सिर्फ NIF होने से कर-निवास तय नहीं होता।"),("आय और गतिविधि","नौकरी, स्वरोज़गार और अन्य आय के अलग दायित्व हो सकते हैं।"),("Portal das Finanças","नियम और घोषणाओं के लिए कर प्राधिकरण के आधिकारिक चैनल का उपयोग करें।")]),
"mudanca-saida.html":("पता बदलना और पुर्तगाल छोड़ना","पता बदलने या देश छोड़ने पर कई संस्थाओं में जानकारी अपडेट करनी पड़ सकती है, केवल AIMA में नहीं।",[("पता","उन संस्थाओं की आवश्यकताएँ जाँचें जो आपके आधिकारिक पते का उपयोग करती हैं।"),("कर और सामाजिक सुरक्षा","देश छोड़ने से कर-निवास, योगदान या लाभ प्रभावित हो सकते हैं।"),("निवास दस्तावेज़","लंबी अनुपस्थिति का आपके दर्जे पर प्रभाव संबंधित प्राधिकरण से पुष्टि करें।")]),
"portugues.html":("पुर्तगाली सीखना","पुर्तगाली भाषा सेवाओं, काम, स्कूल और दैनिक जीवन तक पहुँच आसान बनाती है।",[("कोर्स","सरकारी, नगरपालिका, सामुदायिक या प्रशिक्षण कार्यक्रम खोजें।"),("सही स्तर","दैनिक जीवन, काम, पढ़ाई या प्रमाणन के लक्ष्य के अनुसार स्तर चुनें।"),("नियमित अभ्यास","रोज़ का अभ्यास स्वावलंबन जल्दी बढ़ाता है।")]),
"privacidade.html":("गोपनीयता","Guia सार्वजनिक जानकारी देता है और सामान्य उपयोग के लिए खाता या संवेदनशील दस्तावेज़ अपलोड करने की आवश्यकता नहीं रखता।",[("कम से कम डेटा","पासपोर्ट, निवास कार्ड, पासवर्ड या एक्सेस कोड सार्वजनिक टूल में न भेजें।"),("स्थानीय टूल","कुछ सेटिंग केवल आपके ब्राउज़र में सेव हो सकती हैं।"),("बाहरी साइटें","आधिकारिक वेबसाइटों की अपनी गोपनीयता नीतियाँ होती हैं।")]),
"registos-civis.html":("नागरिक रजिस्ट्रेशन","जन्म, विवाह, मृत्यु और अन्य नागरिक रिकॉर्ड IRN/Justiça के नियमों के अनुसार होते हैं और विदेशी दस्तावेज़ों के प्रमाणीकरण या अनुवाद की जरूरत हो सकती है।",[("रिकॉर्ड का प्रकार","प्रक्रिया आपके आवश्यक रिकॉर्ड या प्रमाणपत्र पर निर्भर करती है।"),("विदेशी दस्तावेज़","मामले के अनुसार apostille, legalisation या translation की जरूरत हो सकती है।"),("आधिकारिक चैनल","मूल दस्तावेज़ देने या भुगतान से पहले Justiça/IRN सेवा की पुष्टि करें।")]),
"situacoes-urgentes.html":("तत्काल स्थितियाँ","खतरा, चिकित्सा आपात स्थिति, हिंसा या दस्तावेज़ खोने पर पहले स्थिति के अनुरूप आपात चैनल का उपयोग करें।",[("तत्काल खतरा","पुर्तगाल में यूरोपीय आपात नंबर 112 है।"),("स्वास्थ्य","गैर-जीवन-धमकी वाली स्थिति में आधिकारिक स्वास्थ्य चैनल से मार्गदर्शन लें।"),("दस्तावेज़","चोरी या खोने पर सबूत रखें और संबंधित अधिकारियों से संपर्क करें।")]),
"termos.html":("उपयोग की शर्तें","Guia सामान्य मार्गदर्शन देता है और प्रशासनिक निर्णय, व्यक्तिगत कानूनी सलाह या सक्षम संस्था की आधिकारिक जानकारी का स्थान नहीं लेता।",[("परिणाम की गारंटी नहीं","Guia अपॉइंटमेंट, अनुमति, वीज़ा, नागरिकता या किसी निर्णय की गारंटी नहीं दे सकता।"),("स्रोत और तारीखें","दो जाँचों के बीच नियम बदल सकते हैं।"),("जिम्मेदार उपयोग","महत्वपूर्ण कदम से पहले वर्तमान शर्तें आधिकारिक स्रोत से जाँचें।")]),
"viver-em-portugal.html":("पुर्तगाल में जीवन","माइग्रेशन प्रक्रियाओं के बाद दैनिक जीवन में स्वास्थ्य, काम, आवास, कर, स्कूल, भाषा, बैंक, घर की सेवाएँ और उपभोक्ता अधिकार शामिल हैं।",[("प्राथमिकताएँ तय करें","सुरक्षित आवास, स्वास्थ्य, काम, दस्तावेज़ और स्कूल से शुरुआत करें।"),("सही सेवा चुनें","हर विषय का अलग सक्षम विभाग है; हर समस्या AIMA से संबंधित नहीं होती।"),("दस्तावेज़ रखें","अनुबंध, रसीद, नोटिस और आधिकारिक दस्तावेज़ व्यवस्थित रखें।")]),
}

DATA["bn"] = {
"404.html":("পৃষ্ঠা পাওয়া যায়নি","চাওয়া পৃষ্ঠাটি নেই অথবা সরানো হয়েছে।",[("হোমে ফিরে যান","হোম, পথসমূহ বা সার্চ ব্যবহার করুন।"),("পুরনো লিংক","পুরনো বুকমার্ক হলে মেনু থেকে সংশ্লিষ্ট বিভাগটি আবার খুলুন।"),("সহায়তা দরকার","যোগাযোগ পৃষ্ঠায় সঠিক সরকারি চ্যানেল খুঁজুন।")]),
"acessibilidade.html":("অ্যাক্সেসিবিলিটি","Guia Migrante PT স্পষ্ট, পাঠযোগ্য এবং কীবোর্ড, মোবাইল ও সহায়ক প্রযুক্তিতে ব্যবহারযোগ্য রাখার লক্ষ্য রাখে।",[("স্পষ্ট কাঠামো","শিরোনাম, লিংক ও বোতামে বোঝা যায় এমন নাম ব্যবহার করা হয়।"),("কীবোর্ড ও কনট্রাস্ট","মাউস ছাড়াও নেভিগেশন ব্যবহারযোগ্য ও পাঠযোগ্য থাকা উচিত।"),("ক্রমাগত উন্নতি","চিহ্নিত অ্যাক্সেসিবিলিটি সমস্যা পরবর্তী সংস্করণে ঠিক করা হয়।")]),
"atualizacoes.html":("আপডেট","এখানে Guia-র গুরুত্বপূর্ণ পরিবর্তন এবং সরকারি উৎস থেকে পুনরায় যাচাই করা তথ্য দেওয়া হয়।",[("কী বদলায়","নতুন সরকারি নিয়ম বা প্রক্রিয়া এলে সংবেদনশীল তথ্য আবার যাচাই করা হয়।"),("পর্যালোচনার তারিখ","গুরুত্বপূর্ণ পৃষ্ঠায় শেষ যাচাইয়ের তারিখ দেখানো হয়।"),("সরকারি উৎস","যথেষ্ট সরকারি ভিত্তি ছাড়া কোনো পরিবর্তন নিশ্চিত তথ্য হিসেবে প্রকাশ করা হয় না।")]),
"discriminacao-apoio.html":("বৈষম্য ও সহায়তা","উৎপত্তি, জাতীয়তা, ভাষা বা অন্যান্য কারণে বৈষম্যের অভিযোগ উপযুক্ত কর্তৃপক্ষের কাছে করা যেতে পারে।",[("প্রমাণ রাখুন","বার্তা, নথি, তারিখ, স্থান ও সাক্ষীর তথ্য সংরক্ষণ করুন।"),("সঠিক চ্যানেল বেছে নিন","পরিস্থিতি অনুযায়ী CIG, ACT, পুলিশ, সরকারি সেবা বা সহায়তা সংস্থা প্রাসঙ্গিক হতে পারে।"),("তাৎক্ষণিক বিপদ","তাৎক্ষণিক বিপদে জরুরি সেবা ব্যবহার করুন।")]),
"escola-familias.html":("স্কুল ও পরিবার","স্কুলে ভর্তি, পড়াশোনার স্বীকৃতি ও শিশু সহায়তা বয়স এবং শিক্ষাগত পরিস্থিতির ওপর নির্ভর করে।",[("ভর্তি","স্কুল বা সংশ্লিষ্ট শিক্ষা সেবার সঙ্গে প্রক্রিয়া যাচাই করুন।"),("স্কুলের নথি","সার্টিফিকেট, ফলাফল, পরিচয়পত্র এবং আগের পড়াশোনার তথ্য রাখুন।"),("পরিবার সহায়তা","ভাষা, বিশেষ প্রয়োজন ও সামাজিক সহায়তার জন্য আলাদা কর্মসূচি থাকতে পারে।")]),
"estado-informacao.html":("তথ্যের অবস্থা","Guia যাচাইকৃত তথ্য, সাময়িকভাবে অপ্রাপ্য উৎস এবং মানব পর্যালোচনা দরকার এমন পরিবর্তন আলাদা করে।",[("যাচাইকৃত","তথ্যের সঙ্গে সরকারি উৎস ও যাচাইয়ের তারিখ থাকে।"),("উৎস অপ্রাপ্য","সাময়িক প্রযুক্তিগত সমস্যায় শেষ বৈধ সরকারি তথ্য স্বয়ংক্রিয়ভাবে মুছে যায় না।"),("পর্যালোচনা দরকার","সংবেদনশীল পরিবর্তন যাচাইয়ের আগে প্রকাশ করা হয় না।")]),
"impostos.html":("কর ও কর-দায়িত্ব","NIF, কর-বাসস্থান, পেশাগত কার্যক্রম এবং ঘোষণা আলাদা বিষয় এবং বাস্তব পরিস্থিতির ওপর নির্ভর করে।",[("কর-বাসস্থান","শুধু NIF থাকলেই কর-বাসস্থান নির্ধারিত হয় না।"),("আয় ও কার্যক্রম","চাকরি, স্বনিয়োজিত কাজ ও অন্যান্য আয়ের আলাদা দায়িত্ব থাকতে পারে।"),("Portal das Finanças","নিয়ম ও ঘোষণার জন্য কর কর্তৃপক্ষের সরকারি চ্যানেল ব্যবহার করুন।")]),
"mudanca-saida.html":("ঠিকানা পরিবর্তন ও পর্তুগাল ত্যাগ","ঠিকানা বদলানো বা দেশ ছাড়লে একাধিক প্রতিষ্ঠানে তথ্য হালনাগাদ করতে হতে পারে, শুধু AIMA-তে নয়।",[("ঠিকানা","যেসব প্রতিষ্ঠান আপনার সরকারি ঠিকানা ব্যবহার করে তাদের নিয়ম যাচাই করুন।"),("কর ও সামাজিক নিরাপত্তা","দেশ ছাড়লে কর-বাসস্থান, অবদান বা সুবিধা প্রভাবিত হতে পারে।"),("বাসস্থান নথি","দীর্ঘ অনুপস্থিতির প্রভাব সংশ্লিষ্ট কর্তৃপক্ষের কাছে যাচাই করুন।")]),
"portugues.html":("পর্তুগিজ শেখা","পর্তুগিজ ভাষা সরকারি সেবা, কাজ, স্কুল এবং দৈনন্দিন জীবন সহজ করে।",[("কোর্স","সরকারি, পৌর, কমিউনিটি বা প্রশিক্ষণ কর্মসূচি খুঁজুন।"),("সঠিক স্তর","দৈনন্দিন জীবন, কাজ, পড়াশোনা বা সনদের লক্ষ্য অনুযায়ী স্তর বেছে নিন।"),("নিয়মিত অনুশীলন","প্রতিদিনের অনুশীলন দ্রুত স্বনির্ভর হতে সাহায্য করে।")]),
"privacidade.html":("গোপনীয়তা","Guia সাধারণ ব্যবহারে অ্যাকাউন্ট বা সংবেদনশীল নথি আপলোড ছাড়াই পাবলিক তথ্য দেয়।",[("ন্যূনতম ডেটা","পাসপোর্ট, রেসিডেন্স কার্ড, পাসওয়ার্ড বা অ্যাক্সেস কোড পাবলিক টুলে পাঠাবেন না।"),("লোকাল টুল","কিছু সেটিং শুধুমাত্র আপনার ব্রাউজারে সংরক্ষিত হতে পারে।"),("বাহ্যিক সাইট","সরকারি ওয়েবসাইটগুলোর নিজস্ব গোপনীয়তা নীতি রয়েছে।")]),
"registos-civis.html":("সিভিল রেজিস্ট্রি","জন্ম, বিবাহ, মৃত্যু ও অন্যান্য সিভিল রেকর্ড IRN/Justiça-র নিয়ম অনুসরণ করে এবং বিদেশি নথির সত্যায়ন বা অনুবাদ দরকার হতে পারে।",[("রেকর্ডের ধরন","প্রক্রিয়া নির্ভর করে কোন রেকর্ড বা সার্টিফিকেট দরকার তার ওপর।"),("বিদেশি নথি","ক্ষেত্রবিশেষে apostille, legalisation বা translation দরকার হতে পারে।"),("সরকারি চ্যানেল","মূল নথি দেওয়া বা অর্থ দেওয়ার আগে Justiça/IRN সেবা যাচাই করুন।")]),
"situacoes-urgentes.html":("জরুরি পরিস্থিতি","বিপদ, চিকিৎসা জরুরি অবস্থা, সহিংসতা বা নথি হারালে প্রথমে পরিস্থিতির উপযুক্ত জরুরি চ্যানেল ব্যবহার করুন।",[("তাৎক্ষণিক বিপদ","পর্তুগালে ইউরোপীয় জরুরি নম্বর 112।"),("স্বাস্থ্য","জীবন-সংশয়হীন পরিস্থিতিতে সরকারি স্বাস্থ্য চ্যানেল থেকে নির্দেশনা নিন।"),("নথি","চুরি বা হারালে প্রমাণ রাখুন এবং সংশ্লিষ্ট কর্তৃপক্ষের সঙ্গে যোগাযোগ করুন।")]),
"termos.html":("ব্যবহারের শর্ত","Guia সাধারণ দিকনির্দেশনা দেয় এবং প্রশাসনিক সিদ্ধান্ত, ব্যক্তিগত আইনি পরামর্শ বা সংশ্লিষ্ট কর্তৃপক্ষের সরকারি তথ্যের বিকল্প নয়।",[("ফলাফলের নিশ্চয়তা নেই","Guia অ্যাপয়েন্টমেন্ট, অনুমতি, ভিসা, নাগরিকত্ব বা অন্য সিদ্ধান্তের নিশ্চয়তা দিতে পারে না।"),("উৎস ও তারিখ","দুই যাচাইয়ের মাঝে নিয়ম বদলাতে পারে।"),("দায়িত্বশীল ব্যবহার","গুরুত্বপূর্ণ পদক্ষেপের আগে বর্তমান শর্ত সরকারি উৎসে যাচাই করুন।")]),
"viver-em-portugal.html":("পর্তুগালে জীবন","মাইগ্রেশন প্রক্রিয়ার পরে দৈনন্দিন জীবনে স্বাস্থ্য, কাজ, বাসস্থান, কর, স্কুল, ভাষা, ব্যাংক, ঘরের সেবা ও ভোক্তা অধিকার অন্তর্ভুক্ত।",[("অগ্রাধিকার ঠিক করুন","নিরাপদ বাসস্থান, স্বাস্থ্য, কাজ, নথি ও স্কুল দিয়ে শুরু করুন।"),("সঠিক সেবা ব্যবহার করুন","প্রতিটি বিষয়ে আলাদা কর্তৃপক্ষ আছে; সব সমস্যা AIMA-র নয়।"),("নথি সংরক্ষণ করুন","চুক্তি, রসিদ, নোটিশ ও সরকারি নথি গুছিয়ে রাখুন।")]),
}

OFFICIAL_LINKS = [
    ("gov.pt", "https://www.gov.pt/"),
    ("AIMA", "https://aima.gov.pt/"),
    ("Justiça", "https://justica.gov.pt/"),
    ("Segurança Social", "https://www.seg-social.pt/"),
]

def load_source_ids(page: str) -> list[str]:
    if not SOURCE_CFG.exists():
        return []
    try:
        data = json.loads(SOURCE_CFG.read_text(encoding="utf-8"))
    except Exception:
        return []
    ids = []
    for src in data.get("sources", []):
        pages = set(src.get("pages", []))
        if page in pages or f"en/{page}" in pages:
            sid = src.get("id")
            if sid:
                ids.append(sid)
    return sorted(set(ids))

def page_html(locale: str, page: str, data) -> str:
    c = UI[locale]
    title, lead, items = data
    source_ids = load_source_ids(page)
    source_meta = f'<meta name="official-source-ids" content="{html.escape(" ".join(source_ids))}">' if source_ids else ''
    cards = ''.join(f'<article class="card"><h3>{html.escape(t)}</h3><p>{html.escape(x)}</p></article>' for t,x in items)
    official = ''.join(f'<a class="card" href="{u}" target="_blank" rel="noopener"><h3>{html.escape(n)}</h3><p>{html.escape(c["source"])}</p></a>' for n,u in OFFICIAL_LINKS)
    if page == "404.html":
        canonical = f"{BASE}/{locale}/404.html"
    else:
        canonical = f"{BASE}/{locale}/{page}"
    return f'''<!doctype html><html lang="{locale}"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#09315c">
<meta name="description" content="{html.escape(lead, quote=True)}"><meta name="last-reviewed" content="{REVIEW_ISO}"><meta name="robots" content="noindex,nofollow">{source_meta}
<title>{html.escape(title)} | Guia Migrante PT</title><link rel="canonical" href="{canonical}"><link rel="alternate" hreflang="pt-PT" href="{BASE}/{page}"><link rel="alternate" hreflang="en" href="{BASE}/en/{page}">
<link rel="icon" href="../favicon.png"><link rel="stylesheet" href="../locale-core.css"><link rel="stylesheet" href="../language-switcher.css"></head><body>
<a class="skip-link" href="#content">{html.escape(c['skip'])}</a><div class="topbar"><div class="container">{html.escape(c['independent'])} · {html.escape(c['verified'])}</div></div>
<header><div class="container header-inner"><a class="brand" href="index.html"><img src="../logo-guia-migrante-256.png" alt=""><span><strong>Guia Migrante PT</strong><small>{html.escape(c['name'])}</small></span></a>
<nav class="desktop-nav"><a href="index.html">{html.escape(c['home'])}</a><a href="percursos.html">{html.escape(c['routes'])}</a><a href="dia-a-dia.html">{html.escape(c['daily'])}</a><a href="contactos.html">{html.escape(c['contacts'])}</a><a href="faq.html">{html.escape(c['faq'])}</a></nav>
<div class="header-actions"><div class="site-lang"><a href="../{page}">PT</a><a href="../en/{page}">EN</a><a class="active" href="{page}">{locale.upper()}</a></div><button class="menu-btn" id="menuButton" type="button" aria-expanded="false" aria-controls="mobileNav" aria-label="{html.escape(c['menu'])}">☰</button></div></div>
<nav class="mobile-nav" id="mobileNav"><a href="index.html">{html.escape(c['home'])}</a><a href="percursos.html">{html.escape(c['routes'])}</a><a href="dia-a-dia.html">{html.escape(c['daily'])}</a><a href="contactos.html">{html.escape(c['contacts'])}</a><a href="faq.html">{html.escape(c['faq'])}</a><a href="seguranca.html">{html.escape(c['security'])}</a></nav></header><div class="brand-stripe"></div>
<div class="review-strip"><div class="container"><span class="review-badge">{html.escape(c['name'])}</span><span>{html.escape(c['stage'])}</span></div></div>
<main id="content"><section class="hero"><div class="container"><span class="kicker">Guia Migrante PT</span><h1>{html.escape(title)}</h1><p>{html.escape(lead)}</p><div class="notice">{html.escape(c['stage'])}</div></div></section>
<section class="content"><div class="container"><div class="section-head"><h2>{html.escape(c['practical'])}</h2></div><div class="grid three">{cards}</div></div></section>
<section class="content white"><div class="container"><div class="section-head"><h2>{html.escape(c['official'])}</h2><p>{html.escape(c['check'])}</p></div><div class="grid three">{official}</div></div></section></main>
<footer><div class="container footer-grid"><div><a class="brand" href="index.html"><img src="../logo-guia-migrante-256.png" alt=""><span><strong style="color:white">Guia Migrante PT</strong></span></a><p class="footer-note">{html.escape(c['legal'])}</p></div><div><div class="footer-title">Portal</div><div class="footer-links"><a href="index.html">{html.escape(c['home'])}</a><a href="percursos.html">{html.escape(c['routes'])}</a><a href="contactos.html">{html.escape(c['contacts'])}</a></div></div></div><div class="container footer-bottom"><span>© 2026 Guia Migrante PT</span><span>{html.escape(c['verified'])}</span></div></footer>
<script>const mb=document.getElementById('menuButton'),mn=document.getElementById('mobileNav');if(mb&&mn)mb.addEventListener('click',()=>{{const o=mn.classList.toggle('open');mb.setAttribute('aria-expanded',String(o));}});</script><script src="../language-switcher.js" defer></script></body></html>'''

def build() -> None:
    total = 0
    for locale in UI:
        target = SITE / locale
        target.mkdir(parents=True, exist_ok=True)
        for page in PAGES:
            (target/page).write_text(page_html(locale, page, DATA[locale][page]), encoding="utf-8")
            total += 1
    print(f"Built remaining staged translations: {total} pages")

if __name__ == "__main__":
    build()
